name: blackhole
description: A Flutter Music Player.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.12.0+21

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  app_links: ^2.2.0
  audio_service: ^0.18.1
  audiotagger: ^2.2.1
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  dart_des: ^1.0.0
  file_picker: ^4.2.0
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_archive: ^4.1.0
  flutter_displaymode: ^0.3.2
  # flutter_downloader: ^1.7.1
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  just_audio: ^0.9.16
  # logging: ^1.0.1
  marquee: ^2.2.0
  material_design_icons_flutter: 5.0.5955-rc.1
  on_audio_query: ^2.5.2
  package_info: ^2.0.2
  palette_generator: ^0.3.2
  path_provider: ^2.0.6
  permission_handler: ^8.2.5
  salomon_bottom_bar: ^3.1.0
  share_plus: ^3.0.4
  supabase: ^0.2.8
  url_launcher: ^6.0.12
  uuid: ^3.0.5
  youtube_explode_dart: 1.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/