name: blackhole
description: A Flutter Music Player.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.13.0+24

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  app_links: ^2.2.0
  audio_service: ^0.18.2
  audiotagger: ^2.2.1
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  dart_des: ^1.0.0
  device_info: ^2.0.3
  file_picker: ^4.2.7
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_archive: ^4.1.0
  flutter_displaymode: ^0.3.2
  # flutter_downloader: ^1.7.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  just_audio: ^0.9.18
  just_audio_libwinmedia: ^0.0.4 # For windows and linux
  # logging: ^1.0.1
  marquee: ^2.2.0
  material_design_icons_flutter: 5.0.5955-rc.1
  on_audio_query: ^2.5.3
  package_info: ^2.0.2
  palette_generator: ^0.3.2
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  salomon_bottom_bar: ^3.2.0
  share_plus: ^3.0.4
  sliding_up_panel: ^2.0.0+1
  supabase: ^0.2.10
  url_launcher: ^6.0.17
  uuid: ^3.0.5
  youtube_explode_dart: 1.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/