name: blackhole
description: A Flutter Music Player.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.11.0+20

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # Audio related
  audiotagger: ^2.2.1
  audio_service: ^0.18.0
  just_audio: ^0.9.12
  on_audio_query: ^2.2.0
  

  # Productivity
  app_links: ^2.2.0
  cached_network_image: ^3.1.0
  dart_des: ^1.0.0
  flutter_archive: ^4.0.1
  flutter_displaymode: ^0.3.2
  # flutter_downloader: ^1.6.1
  # flutter_ffmpeg: ^0.4.2
  html_unescape: ^2.0.0
  # logging: ^1.0.1
  package_info: ^2.0.2
  share_plus: ^2.1.4
  url_launcher: ^6.0.12
  uuid: ^3.0.4
  youtube_explode_dart: ^1.10.6

  
  # UI related
  cupertino_icons: ^1.0.3
  flip_card: ^0.5.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  material_floating_search_bar: ^0.3.4
  palette_generator: ^0.3.1
  salomon_bottom_bar: ^3.1.0

  # Database related
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  supabase: ^0.2.7
  
  # Storage related
  ext_storage:
    git:
      url: git://github.com/GitJournal/ext_storage.git
  file_picker: ^4.1.3
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/